Update package.json
DjLeChuck/recalbox-manager pull request #42
Opened 2017-04-19 13:17 UTC by substring

Add jquery as an explicit dependency

fix #41 
même si je n'ai pas pu tester le resultat. Mais au moins ca compilait

2017-04-19 13:21 UTC, DjLeChuck commented
Ça compilerait oui. 

Mon but est d'effectivement essayer d'utiliser la dépendance jQuery de NPM et ne plus utiliser une dépendance de fichier géré manuellement, mais je dois réglé des conflits avant rencontrés avec certains plugins.

2017-04-19 18:50 UTC, MikaXII commented
Après si tu ne veux pas te faire trop chier aussi sur la gestion des dépendances enlève le '^' avant chaque numéro de version.
Comme ça tu restes as des versions fixe et pas de mauvaises surprise.

2017-04-19 18:51 UTC, MikaXII requested changes
Remove all '^' before each version.

2017-04-19 19:48 UTC, DjLeChuck commented
Corrigé via b7c9560df223c019ebe2522ea0d4cf634103d224

J'ai confondu, c'est pour un projet du taf que j'ai des soucis, pas ici donc ta PR aurait suffit.

2017-04-19 19:48 UTC, closed without merging

2017-04-20 10:28 UTC, substring commented
Cela dit, le commentaire de @MikaXII reste tout à fait pertinent : on n'est pas à l'abri que ca repète un jour parce qu'une dépendance aura changé de version et pètera encore un truc

2017-04-20 10:31 UTC, DjLeChuck commented
Si les paquets respectent le versionning semantic il n'y a pas de problème avec l'utilisation du caret plutôt que du tilde (ou de rien) donc je laisse comme c'est pour le moment.